# Generated by Django 4.1.7 on 2023-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="type",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
