# Generated by Django 4.1.7 on 2023-03-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_cases", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test_case",
            old_name="input",
            new_name="input_value",
        ),
        migrations.RenameField(
            model_name="test_case",
            old_name="output",
            new_name="output_value",
        ),
    ]
