# Generated by Django 4.1.7 on 2023-03-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_answer",
            name="code",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_answer",
            name="language",
            field=models.CharField(default="python", max_length=10),
            preserve_default=False,
        ),
    ]
